name: 'Work Weixin Notifier'
description: 'Get notification to Work Weixin using group Bot'
author: 'jerray'
inputs:
  key:
    description: 'Work Weixin Bot key'
    required: true
  type:
    description: 'Message type, text or markdown'
    default: 'text'
  status:
    description: 'Job status'
    required: true
runs:
  using: 'docker'
  image: 'docker://jerray/work-weixin-notifier:1.1.0'
branding:
  icon: 'send'
  color: 'green'
